use super::Kernel;
use crate::gf2p8lut::{CantorBasisLut, Gf2p8Lut};
use additive_fft_reed_solomon_gf2p8::{FIELD_SIZE, Gf2p8, Gf2p8_11d};
use std::marker::PhantomData;

pub mod unrolled_11d {
    // Include the constants generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/unrolled_lut_kernel_11d.rs"));
}

/// Forward butterfly on one shard pair.
fn butterfly_fwd<G: Gf2p8>(a: &mut [G], b: &mut [G], lut: &[u8; FIELD_SIZE]) {
    for (ai, bi) in a.iter_mut().zip(b.iter_mut()) {
        let t = G::from(lut[bi.into_usize()]); // T * b
        *ai = ai.add(t); // g0 = a + T*b
        *bi = bi.add(*ai); // g1 = g0 + b
    }
}

/// Inverse butterfly on one shard pair.
fn butterfly_inv<G: Gf2p8>(a: &mut [G], b: &mut [G], lut: &[u8; FIELD_SIZE]) {
    for (ai, bi) in a.iter_mut().zip(b.iter_mut()) {
        *bi = bi.add(*ai); //  d' = g0 + g1
        *ai = ai.add(G::from(lut[bi.into_usize()])); //  d  = g0 + T*d'
    }
}

pub fn fft_sharded<G: Gf2p8Lut>(
    basis: &impl CantorBasisLut<G>,
    shards: &mut [G],
    shard_len: usize,
    k: u8,
    beta: G,
) {
    if k == 0 {
        return;
    }
    let half = 1 << (k - 1);
    let twiddle = basis.eval_subspace_poly_lut(k - 1, beta);
    let lut = twiddle.make_mul_lut();

    // Butterfly with one lut computed for the whole pass
    for i in 0..half {
        let (left, right) = shards.split_at_mut((i + half) * shard_len);
        let a = &mut left[i * shard_len..(i + 1) * shard_len];
        let b = &mut right[..shard_len];
        butterfly_fwd(a, b, &lut);
    }

    let next_beta = beta.add(basis.get_basis_point_lut(k - 1));
    let h = half * shard_len;
    fft_sharded(basis, &mut shards[..h], shard_len, k - 1, beta);
    fft_sharded(basis, &mut shards[h..], shard_len, k - 1, next_beta);
}

pub fn ifft_sharded<G: Gf2p8Lut>(
    basis: &impl CantorBasisLut<G>,
    shards: &mut [G],
    shard_len: usize,
    k: u8,
    beta: G,
) {
    if k == 0 {
        return;
    }
    let half = 1 << (k - 1);

    let next_beta = beta.add(basis.get_basis_point_lut(k - 1));
    let h = half * shard_len;
    ifft_sharded(basis, &mut shards[..h], shard_len, k - 1, beta);
    ifft_sharded(basis, &mut shards[h..], shard_len, k - 1, next_beta);

    let twiddle = basis.eval_subspace_poly_lut(k - 1, beta);
    let lut = twiddle.make_mul_lut();

    for i in 0..half {
        let (left, right) = shards.split_at_mut((i + half) * shard_len);
        let a = &mut left[i * shard_len..(i + 1) * shard_len];
        let b = &mut right[..shard_len];
        butterfly_inv(a, b, &lut);
    }
}

pub fn scale<G: Gf2p8Lut>(dst: &mut [G], src: &[G], scalar: G) {
    let lut = scalar.make_mul_lut();
    for (d, s) in dst.iter_mut().zip(src.iter()) {
        *d = G::from(lut[s.into_usize()]);
    }
}

pub fn scale_in_place<G: Gf2p8Lut>(dst: &mut [G], scalar: G) {
    let lut = scalar.make_mul_lut();
    for b in dst.iter_mut() {
        *b = G::from(lut[b.into_usize()]);
    }
}

pub struct LutKernel<G: Gf2p8Lut>(PhantomData<G>);

impl Kernel<Gf2p8_11d> for LutKernel<Gf2p8_11d> {
    fn fft_sharded(
        basis: &impl CantorBasisLut<Gf2p8_11d>,
        shards: &mut [Gf2p8_11d],
        shard_len: usize,
        k: u8,
        beta: Gf2p8_11d,
    ) {
        if beta == Gf2p8_11d::zero() {
            match k {
                0 => {}
                1 => unrolled_11d::fft_sharded_lut_2(shards, shard_len),
                2 => unrolled_11d::fft_sharded_lut_4(shards, shard_len),
                3 => unrolled_11d::fft_sharded_lut_8(shards, shard_len),
                4 => unrolled_11d::fft_sharded_lut_16(shards, shard_len),
                5 => unrolled_11d::fft_sharded_lut_32(shards, shard_len),
                6 => unrolled_11d::fft_sharded_lut_64(shards, shard_len),
                7 => unrolled_11d::fft_sharded_lut_128(shards, shard_len),
                8 => unrolled_11d::fft_sharded_lut_256(shards, shard_len),
                _ => unreachable!("k={k} must be in 2..=8"),
            }
        } else {
            fft_sharded(basis, shards, shard_len, k, beta);
        }
    }

    fn ifft_sharded(
        basis: &impl CantorBasisLut<Gf2p8_11d>,
        shards: &mut [Gf2p8_11d],
        shard_len: usize,
        k: u8,
        beta: Gf2p8_11d,
    ) {
        ifft_sharded(basis, shards, shard_len, k, beta)
    }

    fn scale(dst: &mut [Gf2p8_11d], src: &[Gf2p8_11d], scalar: Gf2p8_11d) {
        scale(dst, src, scalar)
    }

    fn scale_in_place(dst: &mut [Gf2p8_11d], scalar: Gf2p8_11d) {
        scale_in_place(dst, scalar)
    }
}
