use crate::gf2p8lut::{CantorBasisLut, Gf2p8Lut};
use additive_fft_reed_solomon_gf2p8::{Gf2p8, Gf2p8_11d};

pub mod generated {
    // Include the constants generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/tables_11d.rs"));
}

impl Gf2p8Lut for Gf2p8_11d {
    fn mul_lut(self, other: Self) -> Self {
        if self.0 == 0 || other.0 == 0 {
            return 0u8.into();
        }
        let self_log = generated::LOG_TABLE[self.0 as usize] as usize;
        let other_log = generated::LOG_TABLE[other.0 as usize] as usize;
        generated::EXP_TABLE[self_log + other_log].into()
    }

    fn inv_lut(self) -> Self {
        generated::INV_TABLE[self.into_usize()].into()
    }

    fn gfni_mul_matrix(self) -> u64 {
        generated::GFNI_MUL_TABLE[self.into_usize()]
    }
}

#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct CantorBasisLut11d;

impl CantorBasisLut<Gf2p8_11d> for CantorBasisLut11d {
    fn get_basis_point_lut(&self, i: u8) -> Gf2p8_11d {
        generated::CANTOR_BASIS[i as usize].into()
    }

    fn get_subspace_point_lut(&self, i: u8) -> Gf2p8_11d {
        generated::CANTOR_SUBSPACE[i as usize].into()
    }

    fn get_subspace_poly_coeff_lut(&self, k: u8) -> u8 {
        generated::SUBSPACE_POLY_COEFFS[k as usize].into()
    }

    fn eval_subspace_poly_lut(&self, k: u8, x: Gf2p8_11d) -> Gf2p8_11d {
        generated::SUBSPACE_POLY_VALUES[k as usize][x.into_usize()].into()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::RsLut;
    use crate::poly_arith::{
        CantorBasisPolyArith, CantorBasisPolySliceArith, PolySliceArith, poly,
    };
    use additive_fft_reed_solomon_gf2p8::{CantorBasis, CantorBasis11d, FIELD_SIZE, Gf2p8};

    #[test]
    fn mul_lut_correctness() {
        let a: Gf2p8_11d = 0x42.into();
        let b = 0x13.into();
        let expected = a.mul(b);
        let actual = a.mul_lut(b);

        assert_eq!(actual, expected);
    }

    #[test]
    fn gfni_mul_matrix_correctness() {
        let elems = || (0..FIELD_SIZE).map(|i| Gf2p8_11d::from(i as u8));
        for a in elems() {
            for b in elems() {
                let expected = a.mul(b);

                let mat = a.into_mul_matrix();
                let actual = mat.apply(b.into());

                assert_eq!(actual, expected.into());
            }
        }
    }

    fn generate_lch_codeword<const N: usize, const T: usize>(rs: &RsLut<N, T>) -> Vec<Gf2p8_11d> {
        let k = N - T;
        let mut message = vec![Gf2p8_11d::zero(); k];
        let mut parity = vec![Gf2p8_11d::zero(); T];

        for i in 0..k {
            message[i] = Gf2p8_11d::from((T + i) as u8);
        }

        rs.encode_systematic_scalar(&message, &mut parity);

        let mut codeword = vec![Gf2p8_11d::zero(); N];
        codeword[..T].copy_from_slice(&parity);
        codeword[T..].copy_from_slice(&message);
        codeword
    }

    fn generate_sharded_lch_codeword<const N: usize, const T: usize>(
        rs: &RsLut<N, T>,
        shard_len: usize,
    ) -> Vec<Vec<Gf2p8_11d>> {
        let k = N - T;
        let mut message = vec![vec![Gf2p8_11d::zero(); shard_len]; k];
        let mut parity = vec![vec![Gf2p8_11d::zero(); shard_len]; T];

        for i in 0..k {
            for j in 0..shard_len {
                message[i][j] = Gf2p8_11d::from((T + i + j) as u8);
            }
        }

        let message_slices: Vec<&[Gf2p8_11d]> =
            message.iter().map(|shard| shard.as_ref()).collect();
        let mut parity_slices: Vec<&mut [Gf2p8_11d]> =
            parity.iter_mut().map(|shard| shard.as_mut()).collect();

        rs.encode_systematic_sharded(&message_slices, &mut parity_slices);

        let mut codeword = vec![vec![Gf2p8_11d::zero(); shard_len]; N];
        codeword[..T].clone_from_slice(&parity);
        codeword[T..].clone_from_slice(&message);
        codeword
    }

    #[test]
    fn normalization_factors_id() {
        let basis = CantorBasis11d::new();
        let subpoly_luts = basis.gen_all_subspace_poly_luts();
        let norm_factors = basis.gen_normalization_factors(&subpoly_luts, &generated::INV_TABLE);
        assert_eq!(norm_factors, [1u8; 256]);
    }

    #[test]
    fn scalar_fft_ifft_id() {
        let basis = CantorBasisLut11d;
        let mut data = [0u8.into(); 256];

        for i in 0..128 {
            data[i] = Gf2p8_11d::from(i as u8);
        }
        let original = data;

        // k=8 for 256 points, beta=0 for the standard subspace V_8
        basis.fft_scalar(&mut data, 8, 0u8.into());

        assert_ne!(data, original, "FFT should have transformed the data");

        basis.ifft_scalar(&mut data, 8, 0u8.into());

        for i in 0..256 {
            assert_eq!(
                data[i], original[i],
                "IFFT failed to recover coefficient at index {}",
                i
            );
        }
    }

    #[test]
    fn decode_no_errors() {
        decode_no_errors_t::<4, 2>();
        decode_no_errors_t::<8, 4>();
        decode_no_errors_t::<16, 8>();
        decode_no_errors_t::<32, 16>();
        decode_no_errors_t::<64, 32>();
        decode_no_errors_t::<128, 64>();
        decode_no_errors_t::<256, 128>();
    }

    fn decode_no_errors_t<const N: usize, const T: usize>() {
        let rs = RsLut::<N, T>::new();
        let original = generate_lch_codeword(&rs);
        let mut received = original.clone();
        assert!(
            rs.decode_systematic_scalar(&mut received),
            "decode failed for N={N}, T={T}"
        );
        assert_eq!(received, original, "mismatch for N={N}, T={T}");
    }

    #[test]
    fn decode_max_corrupt_parity() {
        decode_max_corrupt_parity_t::<4, 2>();
        decode_max_corrupt_parity_t::<8, 4>();
        decode_max_corrupt_parity_t::<16, 8>();
        decode_max_corrupt_parity_t::<32, 16>();
        decode_max_corrupt_parity_t::<64, 32>();
        decode_max_corrupt_parity_t::<128, 64>();
        decode_max_corrupt_parity_t::<256, 128>();
    }

    fn decode_max_corrupt_parity_t<const N: usize, const T: usize>() {
        let rs = RsLut::<N, T>::new();
        let original = generate_lch_codeword(&rs);
        let mut received = original.clone();

        // Corrupt parity
        for (i, r) in received.iter_mut().take(T / 2).enumerate() {
            *r = (*r).mul((i as u8 + 2).into())
        }

        assert!(
            rs.decode_systematic_scalar(&mut received),
            "Failed to decode corrupt parity at N={N}, T={T}"
        );
        assert_eq!(received, original);
    }

    #[test]
    fn decode_max_corrupt_data() {
        decode_max_corrupt_data_t::<4, 2>();
        decode_max_corrupt_data_t::<8, 4>();
        decode_max_corrupt_data_t::<16, 8>();
        decode_max_corrupt_data_t::<32, 16>();
        decode_max_corrupt_data_t::<64, 32>();
        decode_max_corrupt_data_t::<128, 64>();
        decode_max_corrupt_data_t::<256, 128>();
    }

    fn decode_max_corrupt_data_t<const N: usize, const T: usize>() {
        let rs = RsLut::<N, T>::new();
        let original = generate_lch_codeword(&rs);
        let mut received = original.clone();

        // Corrupt data
        for (i, r) in received.iter_mut().skip(T).take(T / 2).enumerate() {
            *r = (*r).mul((i as u8 + 2).into())
        }

        assert!(
            rs.decode_systematic_scalar(&mut received),
            "Failed to decode corrupt data at N={N}, T={T}"
        );
        assert_eq!(received, original);
    }

    #[test]
    fn recompute_max_corrupt_data() {
        recompute_max_corrupt_data_t::<4, 2>();
        recompute_max_corrupt_data_t::<8, 4>();
        recompute_max_corrupt_data_t::<16, 8>();
        recompute_max_corrupt_data_t::<32, 16>();
        recompute_max_corrupt_data_t::<64, 32>();
        recompute_max_corrupt_data_t::<128, 64>();
        recompute_max_corrupt_data_t::<256, 128>();
    }

    fn recompute_max_corrupt_data_t<const N: usize, const T: usize>() {
        let rs = RsLut::<N, T>::new();
        let original = generate_lch_codeword(&rs);
        let mut received = original.clone();

        // Corrupt data
        for (i, r) in received.iter_mut().skip(T).enumerate() {
            *r = (*r).mul((i as u8 + 2).into())
        }

        rs.recompute_data_from_parity(&mut received);
        assert_eq!(received, original);
    }

    #[test]
    fn poly_mul_lnh_by_zero() {
        let basis = CantorBasisLut11d;
        let zero = [0u8.into(); FIELD_SIZE];

        let mut a = [0u8.into(); FIELD_SIZE];
        a[0] = 0x53.into();
        a[1] = 0xca.into();
        a[3] = 1.into();

        assert_eq!(basis.poly_mul_lnh(&a, &zero), zero);
        assert_eq!(basis.poly_mul_lnh(&zero, &a), zero);
    }

    #[test]
    fn poly_mul_lnh_by_one() {
        let basis = CantorBasisLut11d;
        let mut one = [0u8.into(); FIELD_SIZE];
        one[0] = 1.into();

        let mut a = [0u8.into(); FIELD_SIZE];
        a[0] = 0xab.into();
        a[2] = 0x3f.into();
        a[7] = 0x11.into();

        assert_eq!(basis.poly_mul_lnh(&a, &one), a);
        assert_eq!(basis.poly_mul_lnh(&one, &a), a);
    }

    #[test]
    fn poly_mul_lnh_const_by_const() {
        let basis = CantorBasisLut11d;
        let mut a = [0u8.into(); FIELD_SIZE];
        let a0 = 0x53.into();
        a[0] = a0;

        let mut b = [0u8.into(); FIELD_SIZE];
        let b0 = 0xca.into();
        b[0] = b0;

        let result = basis.poly_mul_lnh(&a, &b);
        assert_eq!(result[0], a0.mul_lut(b0));
        assert_eq!(result[1..], [0u8.into(); FIELD_SIZE - 1]);
    }

    #[test]
    fn poly_mul_lnh_commutes() {
        let basis = CantorBasisLut11d;
        let mut a = [0u8.into(); FIELD_SIZE];
        a[0] = 1.into();
        a[1] = 0xff.into();

        let mut b = [0u8.into(); FIELD_SIZE];
        b[0] = 0x57.into();
        b[2] = 0x83.into();
        b[5] = 0x2a.into();

        assert_eq!(basis.poly_mul_lnh(&a, &b), basis.poly_mul_lnh(&b, &a));
    }

    #[test]
    fn poly_mul_lnh_associative() {
        let basis = CantorBasisLut11d;

        let mut a = [0.into(); FIELD_SIZE];
        a[0] = 3.into();
        a[1] = 9.into();

        let mut b = [0.into(); FIELD_SIZE];
        b[0] = 0xe5.into();
        b[3] = 0x7c.into();

        let mut c = [0.into(); FIELD_SIZE];
        c[0] = 0xaa.into();
        c[1] = 0x55.into();

        let ab_c = basis.poly_mul_lnh(&basis.poly_mul_lnh(&a, &b), &c);
        let a_bc = basis.poly_mul_lnh(&a, &basis.poly_mul_lnh(&b, &c));
        assert_eq!(ab_c, a_bc);
    }

    #[test]
    fn poly_mul_lnh_distributive_over_addition() {
        let basis = CantorBasisLut11d;

        let mut a = [0.into(); FIELD_SIZE];
        a[0] = 0x11.into();
        a[2] = 0x22.into();

        let mut b = [0.into(); FIELD_SIZE];
        b[1] = 0x33.into();
        b[3] = 0x44.into();

        let mut c = [0.into(); FIELD_SIZE];
        c[0] = 0x55.into();
        c[2] = 0x66.into();

        let b_plus_c = poly::add(&b, &c);

        let lhs = basis.poly_mul_lnh(&a, &b_plus_c);
        let rhs = poly::add(&basis.poly_mul_lnh(&a, &b), &basis.poly_mul_lnh(&a, &c));

        assert_eq!(lhs, rhs);
    }

    #[test]
    fn poly_mul_lnh_sum_of_degrees() {
        const DEGREE_A: usize = 3;
        const DEGREE_B: usize = 5;

        let basis = CantorBasisLut11d;

        let mut a = [0.into(); FIELD_SIZE];
        a[DEGREE_A] = 1.into();

        let mut b = [0.into(); FIELD_SIZE];
        b[DEGREE_B] = 1.into();

        let result = basis.poly_mul_lnh(&a, &b);

        assert_eq!(result.degree().unwrap(), DEGREE_A + DEGREE_B);
    }

    #[test]
    fn poly_div_lnh_by_constant_scales_coefficients() {
        let basis = CantorBasisLut11d;
        let c: Gf2p8_11d = 0x53.into();
        let c_inv = c.inv_lut();

        let mut a = [0.into(); FIELD_SIZE];
        a[0] = 0xef.into();
        a[3] = 0xcd.into();
        a[7] = 0xab.into();

        let mut b = [0.into(); FIELD_SIZE];
        b[0] = c;

        let (q, r) = basis.poly_div_lnh(&a, &b).unwrap();

        assert_eq!(r, [0.into(); FIELD_SIZE]);

        for i in 0..FIELD_SIZE {
            assert_eq!(q[i], a[i].mul_lut(c_inv));
        }
    }

    #[test]
    fn field_non_degeneracy() {
        let basis = CantorBasisLut11d;

        for k in 1..=7 {
            let v_k = basis.get_subspace_point_lut(1 << k);
            let v_k_minus_1 = basis.get_subspace_point_lut(1 << (k - 1));
            let s_k_minus_1_v_k = basis.eval_subspace_poly_lut(k - 1, v_k);
            let s_k_minus_1_v_k_minus_1 = basis.eval_subspace_poly_lut(k - 1, v_k_minus_1);
            let k_minus_1 = k - 1;
            assert_ne!(s_k_minus_1_v_k_minus_1, s_k_minus_1_v_k);
        }
    }

    #[test]
    fn subspace_poly_trace() {
        let basis = CantorBasisLut11d;
        let p2: Vec<u8> = (0..8).map(|i| 2u8.pow(i)).collect();

        let points: Vec<_> = p2
            .iter()
            .map(|&p| u8::from(basis.get_subspace_point_lut(p)))
            .collect();
        assert_eq!(points, [1, 214, 152, 146, 86, 200, 88, 231]);
    }

    #[test]
    fn encode_sharded_writes_parity() {
        encode_sharded_writes_parity_t::<4, 2>();
        encode_sharded_writes_parity_t::<8, 4>();
        encode_sharded_writes_parity_t::<16, 8>();
        encode_sharded_writes_parity_t::<32, 16>();
        encode_sharded_writes_parity_t::<64, 32>();
        encode_sharded_writes_parity_t::<128, 64>();
        encode_sharded_writes_parity_t::<256, 128>();
    }

    fn encode_sharded_writes_parity_t<const N: usize, const T: usize>() {
        const SHARD_LEN: usize = 32;
        let rs = RsLut::<N, T>::new();
        let codeword = generate_sharded_lch_codeword(&rs, SHARD_LEN);
        // Verify that the parity shards have been written into.
        for j in 0..T {
            assert_ne!(
                codeword[j],
                vec![Gf2p8_11d::zero(); SHARD_LEN],
                "failed for N={N}, T={T}"
            );
        }
    }

    #[test]
    fn encode_sharded_injective() {
        encode_sharded_generalizes_scalar_t::<4, 2>();
        encode_sharded_generalizes_scalar_t::<8, 4>();
        encode_sharded_generalizes_scalar_t::<16, 8>();
        encode_sharded_generalizes_scalar_t::<32, 16>();
        encode_sharded_generalizes_scalar_t::<64, 32>();
        encode_sharded_generalizes_scalar_t::<128, 64>();
        encode_sharded_generalizes_scalar_t::<256, 128>();
    }

    fn encode_sharded_generalizes_scalar_t<const N: usize, const T: usize>() {
        let rs = RsLut::<N, T>::new();
        let scalar = generate_lch_codeword(&rs);
        let sharded = generate_sharded_lch_codeword(&rs, 1);
        assert_eq!(scalar, sharded.into_iter().flatten().collect::<Vec<_>>());
    }

    #[test]
    fn recompute_max_corrupt_data_sharded() {
        recompute_max_corrupt_data_sharded_t::<4, 2>();
        recompute_max_corrupt_data_sharded_t::<8, 4>();
        recompute_max_corrupt_data_sharded_t::<16, 8>();
        recompute_max_corrupt_data_sharded_t::<32, 16>();
        recompute_max_corrupt_data_sharded_t::<64, 32>();
        recompute_max_corrupt_data_sharded_t::<128, 64>();
        recompute_max_corrupt_data_sharded_t::<256, 128>();
    }

    fn recompute_max_corrupt_data_sharded_t<const N: usize, const T: usize>() {
        const SHARD_LEN: usize = 16;
        let rs = RsLut::<N, T>::new();
        let original = generate_sharded_lch_codeword(&rs, SHARD_LEN);
        let mut received = original.clone();

        // Corrupt data
        for r in received.iter_mut().skip(T) {
            r.fill(Gf2p8_11d::zero());
        }

        let mut received_slices: Vec<&mut [Gf2p8_11d]> =
            received.iter_mut().map(|shard| shard.as_mut()).collect();
        rs.recompute_data_from_parity_sharded(&mut received_slices);
        assert_eq!(received, original);
    }

    #[test]
    fn recover_erasure_shards() {
        recover_erasure_shards_t::<2, 1>();
        recover_erasure_shards_t::<4, 1>();
        recover_erasure_shards_t::<4, 2>();
        recover_erasure_shards_t::<8, 1>();
        recover_erasure_shards_t::<8, 2>();
        recover_erasure_shards_t::<8, 4>();
        recover_erasure_shards_t::<16, 1>();
        recover_erasure_shards_t::<16, 2>();
        recover_erasure_shards_t::<16, 4>();
        recover_erasure_shards_t::<16, 8>();
        recover_erasure_shards_t::<32, 1>();
        recover_erasure_shards_t::<32, 2>();
        recover_erasure_shards_t::<32, 4>();
        recover_erasure_shards_t::<32, 8>();
        recover_erasure_shards_t::<32, 16>();
        recover_erasure_shards_t::<64, 1>();
        recover_erasure_shards_t::<64, 2>();
        recover_erasure_shards_t::<64, 4>();
        recover_erasure_shards_t::<64, 8>();
        recover_erasure_shards_t::<64, 16>();
        recover_erasure_shards_t::<64, 32>();
        recover_erasure_shards_t::<128, 1>();
        recover_erasure_shards_t::<128, 2>();
        recover_erasure_shards_t::<128, 4>();
        recover_erasure_shards_t::<128, 8>();
        recover_erasure_shards_t::<128, 16>();
        recover_erasure_shards_t::<128, 32>();
        recover_erasure_shards_t::<128, 64>();
        recover_erasure_shards_t::<256, 1>();
        recover_erasure_shards_t::<256, 2>();
        recover_erasure_shards_t::<256, 4>();
        recover_erasure_shards_t::<256, 8>();
        recover_erasure_shards_t::<256, 16>();
        recover_erasure_shards_t::<256, 32>();
        recover_erasure_shards_t::<256, 64>();
        recover_erasure_shards_t::<256, 128>();
    }

    fn recover_erasure_shards_t<const N: usize, const T: usize>() {
        const SHARD_LEN: usize = 1;

        let rs = RsLut::<N, T>::new();
        let zero_shard = vec![Gf2p8_11d::zero(); SHARD_LEN];

        let original = generate_sharded_lch_codeword(&rs, SHARD_LEN);
        let mut received = original.clone();
        let mut erasure_positions = Vec::new();

        for (i, shard) in received
            .iter_mut()
            .enumerate()
            .skip(1)
            .take(T * 2 - 1)
            .step_by(2)
        {
            *shard = zero_shard.clone();
            erasure_positions.push(i);
        }

        let mut received_slices: Vec<&mut [Gf2p8_11d]> =
            received.iter_mut().map(|shard| shard.as_mut()).collect();

        assert!(rs.recover_erasure_shards(&mut received_slices, &erasure_positions));
        assert_eq!(received, original, "N={N}, T={T}");
    }
}
